"""Added check flag

Revision ID: 00b891d8a6ce
Revises: d6013f7a725e
Create Date: 2018-09-23 10:37:43.953272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b891d8a6ce'
down_revision = 'd6013f7a725e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done_flag', sa.Boolean(), server_default=sa.text(u'0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'done_flag')
    # ### end Alembic commands ###
