"""Modified Task to add order_by_flag for ordering

Revision ID: d6013f7a725e
Revises: 1e048ccca419
Create Date: 2018-09-20 23:59:44.235958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6013f7a725e'
down_revision = '1e048ccca419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('order_by_flag', sa.Boolean(), server_default=sa.text(u'0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'order_by_flag')
    # ### end Alembic commands ###
